### PR TITLE
Error on no read samples

### LINKED ISSUE #2063: Assertion usedDegree >= 1 instead of error message for mapping to received mesh
This assertion in the time storage:

https://github.com/precice/precice/blob/v3.1.2/src/time/Storage.cpp#L193

Was encountered by two users with wrong configs:

```
ASSERTION FAILED
Location:   Eigen::VectorXd precice::time::Storage::sample(double) const
File:       /home/rodolfo/programas/precice-3.1.2/src/time/Storage.cpp:199
Expression: usedDegree >= 1
Rank:       0
Arguments:  none
```

https://precice.discourse.group/t/multiple-coupling-assertion-failed-eigen-vectorxd-storage-sample-double-const-useddegree-1/2052

https://precice.discourse.group/t/assertion-failed-useddegree-1/2040 

The main issue seems to be applying a read mapping to a received mesh:

config-wrong

### PR DESCRIPTION
**Pull request by fsimonis**
## Main changes of this PR

This PR adds a more refined assertion for this problem when sampling and adds an error message for preventing this assertion from triggering.

The new error reads:
```
ERROR:
Data "Data-Three" cannot be read from mesh "SolverOne-Mesh" as it contains no samples.
This is generally a configuration issue of the data flow.
Check if the data is correctly exchanged to this participant"SolverOne" and mapping to mesh "SolverOne-Mesh".
```

## Motivation and additional information

Closes #2063

## Author's checklist

* [x] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [x] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I added a test to cover the proposed changes in our test suite.
* [ ] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [x] I sticked to C++17 features.
* [x] I sticked to CMake version 3.22.1.
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

### CODE REVIEW

File: src/precice/impl/ParticipantImpl.cpp [hunk 1]
```diff
@@ -1076,9 +1076,14 @@ void ParticipantImpl::readData(
     return;
   }
 
-  ReadDataContext &context          = _accessor->readDataContext(meshName, dataName);
-  const auto       dataDims         = context.getDataDimensions();
-  const auto       expectedDataSize = vertices.size() * dataDims;
+  ReadDataContext &context = _accessor->readDataContext(meshName, dataName);
+  PRECICE_CHECK(context.hasSamples(), "Data \"{}\" cannot be read from mesh \"{}\" as it contains no samples. "
+                                      "This is generally a configuration issue of the data flow. "
+                                      "Check if the data is correctly exchanged to this participant\"{}\" and mapping to mesh \"{}\".",
```
Comment (MakisH) [inline src/precice/impl/ParticipantImpl.cpp:1082]:
```suggestion
                                      "This is typically a configuration issue of the data flow. "
                                      "Check if the data is correctly exchanged to this participant \"{}\" and mapped to mesh \"{}\".",
```

File: docs/changelog/2064.md [hunk 2]
```diff
@@ -0,0 +1 @@
+- Added an error message for data that is read but never mapped or echanged.
```
Comment (MakisH) [inline docs/changelog/2064.md:1]:
```suggestion
- Added an error message for data that is read but never mapped or exchanged.
```

**Review by MakisH — APPROVED** [review]
Wording is good, but I have not tested if the error works. Do you need me to?
Should we maybe add a test as well?

**Comment by fsimonis** [comment]
Sadly we cannot test failures yet.
