### PR TITLE
Handle substeps with remeshing

### LINKED ISSUE #2233: Some remeshing test fail if `substeps="True"`
**Describe your setup**

Operating system (e.g. Linux distribution and version): _Ubuntu 18.04_
preCICE Version: [3d877d5](https://github.com/precice/precice/pull/2220/commits/3d877d55a5fdd49751950a316009b9d927615f44) from https://github.com/precice/precice/pull/2220 or [a8e60c1](https://github.com/precice/precice/commit/a8e60c14e538324c53f826dcf525b10978e9eebc)

**Describe the problem**

If I set `substeps="True"` in all exchanges running `ctest -R precice.Integration/Remeshing/ParallelExplicit/ChangedMapping/RemeshInput` leads to unexpected failures:

```
Test project /home/benjamin/Programming/precice/build
    Start 775: precice.Integration/Remeshing/ParallelExplicit/ChangedMapping/RemeshInput
1/3 Test #775: precice.Integration/Remeshing/ParallelExplicit/ChangedMapping/RemeshInput .........***Failed    5.18 sec
    Start 776: precice.Integration/Remeshing/ParallelExplicit/ChangedMapping/RemeshInput2LI
2/3 Test #776: precice.Integration/Remeshing/ParallelExplicit/ChangedMapping/RemeshInput2LI ......***Failed    2.52 sec
    Start 777: precice.Integration/Remeshing/ParallelExplicit/ChangedMapping/RemeshInputSerial
3/3 Test #777: precice.Integration/Remeshing/ParallelExplicit/ChangedMapping/RemeshInputSerial ...   Passed    0.48 sec

33% tests passed, 2 tests failed out of 3

Label Time Summary:
integration    =   8.18 sec*proc (3 tests)
remeshing      =   8.18 sec*proc (3 tests)

Total Test time (real) =   8.23 sec

The following tests FAILED:
	775 - precice.Integration/Remeshing/ParallelExplicit/ChangedMapping/RemeshInput (Failed)
	776 - precice.Integration/Remeshing/ParallelExplicit/ChangedMapping/RemeshInput2LI (Failed)
```

**Expected behaviour**
`substeps="True"` should be supported by the test.

**Additional context**
* Modifying the test as proposed in #2225 leads to passing tests

### PR DESCRIPTION
**Pull request by fsimonis**
## Main changes of this PR

This PR removes all existing stamples of all ranks if at least one rank resets the mesh.
This is required to keep timestamps consistent among all ranks of a solver.

## Motivation and additional information

Related to and tested by #2198

Closes #2233

## Author's checklist

* [x] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I added a test to cover the proposed changes in our test suite.
* [ ] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [x] I stuck to C++17 features.
* [x] I stuck to CMake version 3.22.1.
* [ ] I squashed / am about to squash all commits that should be seen as one.
* [ ] I ran the systemtests by adding the label `trigger-system-tests` (may be skipped if minor change)

### CODE REVIEW

File: src/precice/impl/ParticipantImpl.cpp [hunk 1]
```diff
@@ -1942,18 +1946,39 @@ ParticipantImpl::MappedSamples ParticipantImpl::mappedSamples() const
...
+  PRECICE_DEBUG("Mesh changes of rank: {}", localMeshChanges);
+
+  // TODO implement int version of allreduceSum
+  std::vector<double> totalMeshChanges(localMeshChanges.size(), 0.0);
+  utils::IntraComm::allreduceSum(localMeshChanges, totalMeshChanges);
+
+  // Convert the doubles to int
+  MeshChanges totalMeshChangesI(totalMeshChanges.begin(), totalMeshChanges.end());
+  PRECICE_DEBUG("Mesh changes of participant: {}", totalMeshChangesI);
+  return totalMeshChangesI;
```
Comment (BenjaminRodenberg) [inline src/precice/impl/ParticipantImpl.cpp:1969]:
```suggestion
  MeshChanges totalMeshChangesInt(totalMeshChanges.begin(), totalMeshChanges.end());
  PRECICE_DEBUG("Mesh changes of participant: {}", totalMeshChangesI);
  return totalMeshChangesInt;
```
?

File: src/precice/impl/ParticipantImpl.cpp [hunk 2]
```diff
@@ -1942,18 +1946,39 @@ ParticipantImpl::MappedSamples ParticipantImpl::mappedSamples() const
...
+}
+
+void ParticipantImpl::clearStamplesOfChangedMeshes(MeshChanges totalMeshChanges)
+{
+  auto meshContexts = _accessor->usedMeshContexts();
+  for (std::size_t i = 0; i < totalMeshChanges.size(); ++i) {
+    if (totalMeshChanges[i] > 0.0) {
+      for (auto d : meshContexts[i]->mesh->data()) {
+        d->timeStepsStorage().clear();
+      }
```
Comment (BenjaminRodenberg) [inline src/precice/impl/ParticipantImpl.cpp:1979]: Do this inside `Mesh` for better encapsulation? E.g. call `mesh->clearTimeStepsStorages()` and implement

```
void Mesh::clearTimeStepsStorages() {
  for (auto d : _data) {
    d->timeStepsStorage().clear();
  }
}
```

Note that there is also a `Mesh::clear()` doing something similar.

**Review by BenjaminRodenberg — APPROVED** [review]
Looks good. Minor refactoring ideas.

File: src/precice/impl/ParticipantImpl.cpp (hunk 2 above)
Comment (fsimonis) [reply src/precice/impl/ParticipantImpl.cpp]: Done

File: src/mesh/Mesh.cpp [hunk 3]
```diff
@@ -263,9 +263,9 @@ void Mesh::clear()
   _tetrahedra.clear();
   _index.clear();
 
+  clearDataStamples();
   for (mesh::PtrData &data : _data) {
     data->values().resize(0);
-    data->timeStepsStorage().clear();
   }
 }
```
Comment (BenjaminRodenberg) [inline src/mesh/Mesh.cpp:270]: Is the change of order here problematic?

`data->values().resize(0)` is something we would like to remove in the long term but currently I would be careful with changing the order of the statements if it is not necessary. There are sometime strange side-effects when the storage and the values interact with each other.

Comment (fsimonis) [reply src/mesh/Mesh.cpp:270]: There are no side effects here and this should hopefully go away soon.
