### PR TITLE
Fix skipping initial mappings in parallel

### LINKED ISSUE #1998: Using `initialize="true"` leads to inconsistent decision for skipping zero sample
**Describe your setup**

preCICE Version: 3.1.0

**Describe the problem**
My testcase (doesn't depend on the number of participants) requires to use `<exchange... intialize="true"/>`. I run in parallel and not all participants are part of the coupling interface. In our current implementation, we call `mapData` with `skipZero=true` and use a logical `&&` to connect it to data being zero or not

https://github.com/precice/precice/blob/4c3f798231b131583106b882b36af175b6b99538/src/precice/impl/DataContext.cpp#L129

The other participant nicely provides initial data and the condition `stample.sample.values.isZero()` evaluates to `false` for all participants, who are part of the coupling interface. However, for all participants not part of the interface,  `stample.sample.values.size() == 0`, and therefore `stample.sample.values.isZero()` evaluates to `true`.

This inconsistencies leads to decisions on individual ranks to enter `mapData` or skip it. However, we have mappings relying on collective MPI operations, such as the Eigen RBF or (didn't check, but should apply) our PETSc based mappings, such that we run into a deadlock for these cases.

The decision to skip the zero sample or not should be consistent across ranks. Not all mapping variants rely on collective MPI operations, but from a logical perspective, it would make sense to synchronize the decision (in my case, the logging on the primary rank was also wrong, as it didn't hold any interface fraction).

**Step To Reproduce**
1. Setup a participant and run it at least on two ranks. One of the ranks should not be part of the interface. Configure `initialize="true"` and initialize non-zero data.
2. Configure one of our global RBF mapping variants.
3. Run into a deadlock.

### PR DESCRIPTION
**Pull request by davidscn**
## Main changes of this PR

Fixes the decision for skipping initial data containing only zero data in parallel runs by making the decision consistent across ranks. 

## Motivation and additional information

Provided in #1998 and resolves #1998

## Author's checklist

* [x] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [x] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [x] I added a test to cover the proposed changes in our test suite.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

### CODE REVIEW

File: src/precice/impl/DataContext.cpp [hunk 1]
```diff
@@ -126,7 +126,7 @@ int DataContext::mapData(std::optional<double> after, bool skipZero)
           dataDims,
           Eigen::VectorXd::Zero(dataDims * mapping.getOutputMesh()->nVertices())};
 
-      bool skipMapping = skipZero && stample.sample.values.isZero();
+      bool skipMapping = skipZero && (utils::IntraComm::l2norm(stample.sample.values) < math::NUMERICAL_ZERO_DIFFERENCE);
```
Comment (fsimonis) [inline src/precice/impl/DataContext.cpp:129]: This is now an unconditional collective for every mapped data, which sounds pretty expensive to me.

An elegant and easy way to prevent this could be:
```suggestion
      bool skipMapping = skipZero && mapping.usesCollectives() && (utils::IntraComm::l2norm(stample.sample.values) < math::NUMERICAL_ZERO_DIFFERENCE);
```

This prevents the `l2norm` collective when `mapping.usesCollectives() == false`.

This could be as simple as
```cpp
// in Mapping.hpp
virtual bool usesCollectives() const = 0;
// for RBF
bool usesCollectives() const override { return true };
// for the NN, NNG and NP (as long as scaled-consistent is locked to serial participants)
bool usesCollectives() const override { return false };
```

Comment (davidscn) [reply src/precice/impl/DataContext.cpp:129]: > This is now an unconditional collective for every mapped data

Actually no, according to the C++ standard, the logical AND (&&) and logical OR (||) operators perform short-circuit evaluation. The boolean is only `true` in the 'initial' skip. In all other cases, the boolean is `false` and the `l2norm` is not evaluated.

Comment (uekerman) [reply src/precice/impl/DataContext.cpp:129]: @fsimonis But your solution no longer checks whether the data is actually zero in case of non-collective mappings?

Comment (fsimonis) [reply src/precice/impl/DataContext.cpp:129]: > short-circuit evaluation

:man_facepalming: _true_

So currently, we have a collective for every data-sample when we initialize data.
While not tragic, that still hurts performance for NN/NP etc.

> But your solution no longer checks whether the data is actually zero in case of non-collective mappings?

This should do the trick:

```suggestion
      bool skipMapping = skipZero && ( mapping.usesCollective() ? (utils::IntraComm::l2norm(stample.sample.values) < math::NUMERICAL_ZERO_DIFFERENCE) : stample.sample.values.isZero());
```

Comment (davidscn) [reply src/precice/impl/DataContext.cpp:129]: > While not tragic, that still hurts performance for NN/NP

Let's not worry about this at this point and introduce complexity. It's an initialization cost and for really large cases, establishing the connection and computing the communication maps takes significantly more time (I measured this back then on Supermuc for my mapping experiments). If we observe issues in the future, we can still fix it in the future.

Comment (fsimonis) [reply src/precice/impl/DataContext.cpp:129]: Low gain at a low added complexity. I don't have a strong opinion here.
@uekerman your call.

Comment (davidscn) [reply src/precice/impl/DataContext.cpp:129]: > Low gain at a low added complexity. I don't have a strong opinion here.

Well, your logic is incomplete. The PUM doesn't use collectives, whereas the other RBFs do. Also, the code changes might appear trivial, but introduce a dependency of the mapping package to the data context. Modifying one of the mapping to incorporate MPI calls would require changes here as well. If we add GPU to the PUM, we might need such collective MPI calls, how do we handle this then? So we would need separate tests for all cases, which is then yet another todo.

Comment (davidscn) [reply src/precice/impl/DataContext.cpp:129]: I will add a comment to make the short-circuit evaluation more apparent.

Comment (davidscn) [inline src/precice/impl/DataContext.cpp:129]:
```suggestion
      // Note that the l2norm is only computed during initialization due to short-circuit evaluation in C++
      bool skipMapping = skipZero && (utils::IntraComm::l2norm(stample.sample.values) < math::NUMERICAL_ZERO_DIFFERENCE);
```

**Review by fsimonis — APPROVED** [review]
Looks good!
Please squash and merge.
