### PR TITLE
Fix info log for linear-cell interpolation mapping

### LINKED ISSUE #1565: Confusing fall-back warnings in linear-cell interpolation
**Describe your setup**

preCICE Version: 1965ceb

**Describe the problem**
Using the `linear-cell-interpolation` mapping without providing any connectivity leads to the following warnings/logs

```bash
---[precice] WARNING:  2D Mesh "Solid-Mesh" does not contain triangles. Linear cell interpolation falls back to nearest projection mapping.
---[precice]  All vertices are inside cells, no fallback to Nearest-Projection required
```

This is very confusing and some people might think that the LCI mapping just works (without providing connectivity.

**Step To Reproduce**
1. Select a tutorial case without connectivity (I used the perpendicular-flap)
2. exchange one of the mappings to use linear-cell-interpolation

**Expected behaviour**
A clear warning saying what is actually wrong and what should be changed.

FYI: @boris-martin

### PR DESCRIPTION
**Pull request by davidscn**
## Main changes of this PR

Fixes the info log for linear-cell interpolation mapping.

## Motivation and additional information

See #1565, closes #1565 

## Author's checklist

* [x] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
<del> [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release </del>
<del> I added a test to cover the proposed changes in our test suite. </del>

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

### CODE REVIEW

File: src/mapping/LinearCellInterpolationMapping.cpp [hunk 1]
```diff
@@ -90,16 +93,21 @@ void LinearCellInterpolationMapping::computeMapping()
     }
   }
 
-  if (!fallbackStatistics.empty() && !missingConnectivity) {
```
Comment (boris-martin) [inline src/mapping/LinearCellInterpolationMapping.cpp:93]: Would probably be cleaner with two levels of block: `if (!fallbackStatistics.empty())` then check for `hasConnectivity`

**Review by boris-martin — APPROVED** [review]

File: src/mapping/LinearCellInterpolationMapping.cpp (hunk 1 above)
Comment (davidscn) [reply src/mapping/LinearCellInterpolationMapping.cpp:93]: I don't like nested of blocks, as they somehow make the control flow more complex. However, I adjusted it
