### PR TITLE
Fix missing vtu data pieces in master pvtu file

### LINKED ISSUE #1102: Missing `vtu` data pieces on exported meshes
**Describe your setup**

Operating system (e.g. Linux distribution and version): _CentOS 8_
preCICE Version: 2.2.1 as well as 2.3.0

**Describe the problem**
For our parallel exports, every rank exports `vtu` files and the master rank exports the `master.pvtu` file containing a list of relevant rank files. However, in case a `provided` mesh is not send to other participants and exported, the `master.pvtu` file does not contain the relevant files`

```xml
...
    <PPointData Scalars="Rank " Vectors="Displacement ">
         <PDataArray type="Int32" Name="Rank" NumberOfComponents="1"/>
         <PDataArray type="Float64" Name="Displacement" NumberOfComponents="3"/>
      </PPointData>
   </PUnstructuredGrid>
```
The export of the `provided` *and* sent (to another participant) mesh looks as it should:

```xml
...
      <PPointData Scalars="Rank " Vectors="Stress ">
         <PDataArray type="Int32" Name="Rank" NumberOfComponents="1"/>
         <PDataArray type="Float64" Name="Stress" NumberOfComponents="3"/>
      </PPointData>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r1.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r5.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r9.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r17.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r21.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r25.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r33.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r37.vtu"/>
      <Piece Source="Fluid-Mesh-Faces-Fluid.init_r41.vtu"/>
   </PUnstructuredGrid>
``` 
Opening the defect file in paraView results just in an empty file.

**Step To Reproduce**
1. Run a parallel coupled simulation with vtk exports on a mesh you don't send to other participants
2. look at the resulting vtks

**Expected behaviour**
The defect file should contain the list of relevant files

### PR DESCRIPTION
**Pull request by DavidSCN**
## Main changes of this PR
Fixes a bug where an empty vertex distribution leads to missing exported data pieces. Resolves #1102 

## Motivation and additional information
Instead of the vertex distribution, I selected now the vertex offsets, which work reliably.

## Author's checklist

* [x] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [x] I ran `make format` to ensure everything is formatted correctly.
* [x] I sticked to C++14 features.
* [x] I sticked to CMake version 3.10.
* [x] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

### CODE REVIEW

**Comment by DavidSCN** [comment]
This approach fails in the unit test right now, since we explicitly set the vertexDistribution for the unit test

https://github.com/precice/precice/blob/e523aef6181447c794dbaa74368d5dcb8c1a6443/src/io/tests/ExportVTUTest.cpp#L61-L64

I would replace these lines by the vertex offsets in order to adapt the unit test to work with the current implementation. Also, I need to add a check for the size of the `offset` vector. A conceptual feedback before adjusting this would be useful. Note, that the current approach is much more robust in terms of real applications and actually fixes the bug (the unit test just complies with the implementation).

File: src/io/ExportXML.cpp [hunk 1]
```diff
@@ -79,10 +79,14 @@ void ExportXML::writeMasterFile(
...
+  const auto &offsets = mesh.getVertexOffsets();
+  PRECICE_ASSERT(offsets.size() > 0);
+  if (offsets[0] > 0) {
+    outMasterFile << "      <Piece Source=\"" << name << "_" << 0 << getPieceExtension() << "\"/>\n";
+  }
+  for (int i = 1; i < utils::MasterSlave::getSize(); i++) {
+    PRECICE_ASSERT(i < offsets.size());
+    if (offsets[i] - offsets[i - 1] > 0) {
       //only non-empty subfiles
       outMasterFile << "      <Piece Source=\"" << name << "_" << i << getPieceExtension() << "\"/>\n";
```
Comment (fsimonis) [inline src/io/ExportXML.cpp:91]: We can use `allSlaves()` to make this a bit more expressive.
 
```suggestion
  for (auto rank : utils::MasterSlave::allSlaves()) {
    PRECICE_ASSERT(rank < offsets.size());
    if (offsets[rank] - offsets[rank - 1] > 0) {
      //only non-empty subfiles
      outMasterFile << "      <Piece Source=\"" << name << "_" << rank << getPieceExtension() << "\"/>\n";
```

**Review by fsimonis — APPROVED** [review]
Nice!
One comment. After that, feel free to squash and merge.
