### PR TITLE
Fix locking in SocketSendQueue

### LINKED ISSUE #1243: Undefined behavior in communication
**Describe your setup**

preCICE Version: 2.3.0

**Describe the problem**
While running several larger validation cases, I face a rather randomly occurring abort related to the communication in preCICE. The nasty thing: recompiling preCICE in `Debug` removes (at least until now) any aborts, i.e., I mostly face this bug when compiling in `Release` or `RelWithDebug`. For this reason, I tried to compile preCICE in `Release` mode and enabled debug messages as well as assertions which generated the following stacktrace when failing

```bash
[19] #0  Foam::error::printStack(Foam::Ostream&) at ??:?
[19] #1  Foam::sigSegv::sigHandler(int) at ??:?
[19] #2  ? in /lib/x86_64-linux-gnu/libpthread.so.0
[19] #3  precice::com::SocketSendQueue::process() in ~/local/lib/libprecice.so.2
[19] #4  precice::com::SocketSendQueue::dispatch(std::shared_ptr<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::executor> >, boost::asio::const_buffers_1, std::function<void ()>) in ~/local/lib/libprecice.so.2
[19] #5  precice::com::SocketCommunication::aSend(std::vector<double, std::allocator<double> > const&, int) in ~/local/lib/libprecice.so.2
[19] #6  precice::m2n::PointToPointCommunication::send(precice::span<double const, 18446744073709551615ul>, int) in ~/local/lib/libprecice.so.2
[19] #7  precice::m2n::M2N::send(precice::span<double const, 18446744073709551615ul>, int, int) in ~/local/lib/libprecice.so.2
[19] #8  precice::cplscheme::BaseCouplingScheme::sendData(std::shared_ptr<precice::m2n::M2N> const&, std::map<int, std::shared_ptr<precice::cplscheme::CouplingData>, std::less<int>, std::allocator<std::pair<int const, std::shared_ptr<precice::cplscheme::CouplingData> > > > const&) in ~/local/lib/libprecice.so.2
[19] #9  precice::cplscheme::ParallelCouplingScheme::exchangeDataAndAccelerate() in ~/local/lib/libprecice.so.2
[19] #10  precice::cplscheme::BaseCouplingScheme::advance() in ~/local/lib/libprecice.so.2
[19] #11  precice::impl::SolverInterfaceImpl::advance(double) in ~/local/lib/libprecice.so.2
[19] #12  preciceAdapter::Adapter::advance() at ??:?
[19] #13  preciceAdapter::Adapter::execute() at ??:?
[19] #14  Foam::functionObjects::preciceAdapterFunctionObject::execute() at ??:?
[19] #15  Foam::functionObjectList::execute() at ??:?
[19] #16  Foam::Time::run() const at ??:?
[19] #17  ? at ??:?
[19] #18  __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
[19] #19  ? at ??:?
```
and the corresponding debug log from the master rank

<details>
  <summary>Click to expand</summary>

```log
(0) [impl::SolverInterfaceImpl]:448 in advance:  Handle exports
(0) [utils::Events]:40 in start:  Started event solver.advance
(0) [utils::Events]:59 in stop:  Stopped event advance
(0) [utils::Events]:59 in stop:  Stopped event solver.advance
(0) [utils::Events]:40 in start:  Started event advance
(0) [cplscheme::BaseCouplingScheme]:336 in getThisTimeWindowRemainder:  return 0
(0) [cplscheme::BaseCouplingScheme]:336 in getThisTimeWindowRemainder:  return 0
(0) [cplscheme::BaseCouplingScheme]:336 in getThisTimeWindowRemainder:  return 0
(0) [impl::SolverInterfaceImpl]:433 in advance:  Advance coupling scheme
(0) [cplscheme::BaseCouplingScheme]:336 in getThisTimeWindowRemainder:  return 0
(0) [cplscheme::ParallelCouplingScheme]:60 in exchangeDataAndAccelerate:  Sending data...
(0) [utils::Events]:40 in start:  Started event advance/m2n.sendData
(0) [utils::Events]:59 in stop:  Stopped event advance/m2n.sendData
(0) [cplscheme::BaseCouplingScheme]:94 in sendData:  Number of sent data sets = 1
(0) [cplscheme::ParallelCouplingScheme]:62 in exchangeDataAndAccelerate:  Receiving data...
(0) [m2n::M2N]:314 in receive:  receive(bool): false
(0) [utils::Events]:40 in start:  Started event advance/m2n.receiveData
(0) [utils::Events]:59 in stop:  Stopped event advance/m2n.receiveData
(0) [cplscheme::BaseCouplingScheme]:109 in receiveData:  Number of received data sets = 1
(0) [cplscheme::BaseCouplingScheme]:215 in advance:  No convergence achieved
(0) [impl::SolverInterfaceImpl]:1599 in mapReadData:  Map read data "Displacement" to mesh "Fluid-Mesh-Nodes"
(0) [utils::Events]:40 in start:  Started event advance/map.rbf.mapData.FromSolid-writeToFluid-Mesh-Nodes
(0) [com::MPICommunication]:319 in receive:  Received 126 from rank 1
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 2
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 3
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 4
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 5
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 6
(0) [com::MPICommunication]:319 in receive:  Received 90 from rank 7
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 8
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 9
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 10
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 11
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 12
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 13
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 14
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 15
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 16
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 17
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 18
(0) [com::MPICommunication]:319 in receive:  Received 348 from rank 19
(0) [com::MPICommunication]:319 in receive:  Received 114 from rank 20
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 21
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 22
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 23 
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 24
(0) [com::MPICommunication]:319 in receive:  Received 240 from rank 25
(0) [com::MPICommunication]:319 in receive:  Received 135 from rank 26
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 27
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 28
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 29
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 30
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 31
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 32
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 33
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 34
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 35
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 36
(0) [com::MPICommunication]:319 in receive:  Received 90 from rank 37
(0) [com::MPICommunication]:319 in receive:  Received 54 from rank 38
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 39
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 40
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 41
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 42
(0) [com::MPICommunication]:319 in receive:  Received 72 from rank 43
(0) [com::MPICommunication]:319 in receive:  Received 36 from rank 44
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 45
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 46
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 47
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 48
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 49
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 50
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 51
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 52
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 53
(0) [utils::Events]:59 in stop:  Stopped event advance/map.rbf.mapData.FromSolid-writeToFluid-Mesh-Nodes
(0) [impl::DataContext]:119 in mapData:  Mapped values = <Empty Range>
(0) [impl::SolverInterfaceImpl]:446 in advance:  iteration: 2 of 30, time-window: 621, time: 6.2 of 30, time-window-size: 0.01, max-timestep-length: 0.01, ongoing: yes, time-window-complete: no, read-iteration-checkpoint 
(0) [impl::SolverInterfaceImpl]:448 in advance:  Handle exports
(0) [utils::Events]:40 in start:  Started event solver.advance
(0) [utils::Events]:59 in stop:  Stopped event advance
(0) [utils::Events]:59 in stop:  Stopped event solver.advance
(0) [utils::Events]:40 in start:  Started event advance 
(0) [cplscheme::BaseCouplingScheme]:336 in getThisTimeWindowRemainder:  return 0
(0) [cplscheme::BaseCouplingScheme]:336 in getThisTimeWindowRemainder:  return 0
(0) [cplscheme::BaseCouplingScheme]:336 in getThisTimeWindowRemainder:  return 0
(0) [impl::SolverInterfaceImpl]:433 in advance:  Advance coupling scheme
(0) [cplscheme::BaseCouplingScheme]:336 in getThisTimeWindowRemainder:  return 0
(0) [cplscheme::ParallelCouplingScheme]:60 in exchangeDataAndAccelerate:  Sending data...
(0) [utils::Events]:40 in start:  Started event advance/m2n.sendData
(0) [utils::Events]:59 in stop:  Stopped event advance/m2n.sendData
(0) [cplscheme::BaseCouplingScheme]:94 in sendData:  Number of sent data sets = 1
(0) [cplscheme::ParallelCouplingScheme]:62 in exchangeDataAndAccelerate:  Receiving data...
(0) [m2n::M2N]:314 in receive:  receive(bool): false
(0) [utils::Events]:40 in start:  Started event advance/m2n.receiveData
(0) [utils::Events]:59 in stop:  Stopped event advance/m2n.receiveData
(0) [cplscheme::BaseCouplingScheme]:109 in receiveData:  Number of received data sets = 1
(0) [cplscheme::BaseCouplingScheme]:215 in advance:  No convergence achieved
(0) [impl::SolverInterfaceImpl]:1599 in mapReadData:  Map read data "Displacement" to mesh "Fluid-Mesh-Nodes"
(0) [utils::Events]:40 in start:  Started event advance/map.rbf.mapData.FromSolid-writeToFluid-Mesh-Nodes
(0) [com::MPICommunication]:319 in receive:  Received 126 from rank 1
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 2
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 3
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 4
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 5
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 6
(0) [com::MPICommunication]:319 in receive:  Received 90 from rank 7
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 8
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 9
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 10
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 11
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 12
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 13
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 14
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 15
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 16
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 17
(0) [com::MPICommunication]:319 in receive:  Received 0 from rank 18
```

</details>

I'm almost certain that this is an actual bug in preCICE, as it was reported multiple times on discourse, see e.g. here https://precice.discourse.group/t/forrtl-severe-174-occurred-during-simulation/1010 and here https://precice.discourse.group/t/openfoam-dealii-simulations-with-large-fluid-meshes-crash/879

The stacktrace in plain release mode gives only little information on what is going on:

```bash
41] #0  Foam::error::printStack(Foam::Ostream&) at ??:?
[41] #1  Foam::sigSegv::sigHandler(int) at ??:?
[41] #2  ? in /lib/x86_64-linux-gnu/libpthread.so.0
[41] #3  precice::com::SocketSendQueue::process() in ~/local/lib/libprecice.so.2
[41] #4  ? in ~/local/lib/libprecice.so.2
[41] #5  ? in ~/local/lib/libprecice.so.2
[41] #6  boost::asio::detail::scheduler::run(boost::system::error_code&) in ~/local/lib/libprecice.so.2
[41] #7  ? in ~/local/lib/libprecice.so.2
[41] #8  ? in /usr/local.nfs/sw/gcc/gcc-9.2.0/lib64/libstdc++.so.6
[41] #9  ? in /lib/x86_64-linux-gnu/libpthread.so.0
[41] #10  clone in /lib/x86_64-linux-gnu/libc.so.6
```
I also tried to build everything in debug mode and use Valgrind in order to boil it down further, but there are too many standard/boost libraries involved so that this output isn't really helpful either. However, it kind of proofs that there is actually something wrong in our memory handling (assuming I'm guessing right that this is the same bug/memory leak):
 
```bash
==1275644== 34 (32 direct, 2 indirect) bytes in 1 blocks are definitely lost in loss record 23 of 56
==1275644==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==1275644==    by 0x39EE5BD8: ???
==1275644==    by 0x39EEDF4B: ???
==1275644==    by 0x39E0AA0D: ???
==1275644==    by 0x39E7D9C1: ???
==1275644==    by 0x2C8F4FDD: ??? (in /usr/lib/x86_64-linux-gnu/libevent-2.1.so.7.0.0)
==1275644==    by 0x2C8F587E: event_base_loop (in /usr/lib/x86_64-linux-gnu/libevent-2.1.so.7.0.0)
==1275644==    by 0x39E43D55: ???
==1275644==    by 0x24153608: start_thread (pthread_create.c:477)
==1275644==    by 0x2428D132: clone (clone.S:95)
```

**Step To Reproduce**
This is somewhat the critical point of this bug. I have a setup which fails regularly, but there is (1.) no guarantee when it fails and (2.) it is rather large. I'm a bit puzzled how to move forward here in general, but it is quite annoying and seems to be more common than we currently know.

### PR DESCRIPTION
**Pull request by fsimonis**
## Main changes of this PR

This PR fixes incorrect locking in the SocketSendQueue, which may occasinally lead to crashes when using a socket communication.

## Motivation and additional information

Closes #1243

## Author's checklist

* [x] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [x] I ran `make format` to ensure everything is formatted correctly.
* [x] I sticked to C++14 features.
* [x] I sticked to CMake version 3.16.3.
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

### CODE REVIEW

File: src/com/SocketSendQueue.hpp [hunk 1]
```diff
@@ -36,9 +37,12 @@ class SocketSendQueue {
...
   };
 
+  /// The queue, containing items to asynchronously send using boost.asio.
   std::deque<SendItem> _itemQueue;
-  std::mutex           _sendMutex;
-  bool                 _ready = true;
+  /// The mutex protecting access to the queue
+  std::mutex _queueMutex;
+  /// Is the queue allowed to start another asynchronous send?
+  std::atomic_bool _ready{true};
```
Comment (DavidSCN) [inline src/com/SocketSendQueue.hpp:45]: Do we need the atomic boolean here, considering that the queue is now locked anyway?

Comment (fsimonis) [reply src/com/SocketSendQueue.hpp:45]: Good point. This is due to strange interface, I'll clarify it.

File: src/com/SocketSendQueue.cpp [hunk 2]
```diff
@@ -23,24 +23,32 @@ void SocketSendQueue::dispatch(std::shared_ptr<Socket>      sock,
                                boost::asio::const_buffers_1 data,
                                std::function<void()>        callback)
 {
+  std::lock_guard<std::mutex> lock(_queueMutex);
```
Comment (DavidSCN) [inline src/com/SocketSendQueue.cpp:26]: Stupid question: Couldn't this lead to a deadlock when locking the mutex here and trying to lock it later down in the `process()->sendComplete()` function? We had an extra scope for the lock previously.

Comment (fsimonis) [reply src/com/SocketSendQueue.cpp:26]: That's not a stupid question. Boost.asio guarantees that the handler (or the lambda in this case) will not be invoked from the calling function.

> Regardless of whether the asynchronous operation completes immediately or not, the handler will not be invoked from within this function. On immediate completion, invocation of the handler will be performed in a manner equivalent to using [post](https://www.boost.org/doc/libs/1_71_0/doc/html/boost_asio/reference/post.html).

[Source](https://www.boost.org/doc/libs/1_71_0/doc/html/boost_asio/reference/async_write/overload1.html)

Comment (DavidSCN) [reply src/com/SocketSendQueue.cpp:26]: Alright, thanks

**Review by DavidSCN — APPROVED** [review]
Good to go from my side. The error is gone for all of my testcases. Not sure why we actually need to increase the timeout time and how it is related to the changes here, but ok.

**Comment by fsimonis** [comment]
The testsuites have grown and started to run very close to the timeout. (At least on the GitHub runners)
