### PR TITLE
Do not interpolate data for existing timestamps

### LINKED ISSUE #1752: Do not interpolate data for existing timestamps
**Please describe the problem you are trying to solve.**

When reading data for a given dt, then `time::storage` creates a b-spline and interpolates based on it.
Only exception is if there is only a single data point.

If a sample already exists at the given dt, then the time storage still interpolates instead of returning the matching sample.

**Describe the solution you propose.**

Directly use a sample if the requested time matches its timestamp.

**Additional context**

https://github.com/precice/precice/pull/1746

### PR DESCRIPTION
**Pull request by NiklasKotarsky**
## Main changes of this PR
Changes storage so that it returns the existing values instead of interpolating them. 

## Motivation and additional information
Fixes  #1752

## Author's checklist

* [x] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [x] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [x] I added a test to cover the proposed changes in our test suite.
* [ ] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [x] I sticked to C++17 features.
* [x] I sticked to CMake version 3.16.3.
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [x] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

### CODE REVIEW

File: src/time/Storage.cpp [hunk 1]
```diff
@@ -163,10 +163,18 @@ Eigen::VectorXd Storage::sample(double time) const
...
 
-  auto data = getTimesAndValues();
+  auto [times, values] = getTimesAndValues();
+
+  //Return the sample corresponding to time if it exists
+  for (int i = 0; i < times.size(); i++) {
+    if (math::equals(times[i], time)) {
+      return values.col(i);
+    }
+  }
```
Comment (BenjaminRodenberg) [inline src/time/Storage.cpp:173]: This could be implemented more efficiently: `times` are ascending. Therefore, I would suggest something in this direction:
```
int i = 0;
while(math::smallerEquals(times[i], time) {
    if(math::equals(times[i], time)) {
        return values.col(i);
    }
    i++;
}
```
Maybe even put this into a private function of `Storage`:
```
int findTimeId(time) const {
    int i = 0;
    while(math::smallerEquals(_stampleStorage[i].timestamp, time) {
        if(math::equals(_stampleStorage[i].timestamp, time)) {
        return return i;
        }
    i++;
    }
    return -1;  // time not found in times
}
```

Comment (BenjaminRodenberg) [reply src/time/Storage.cpp:173]: If we start with efficiency here: You can move `getTimesAndValues()` inside the `if(!_bspline.has_value())` branch, because you don't need it outside. This results in

```
Eigen::VectorXd Storage::sample(double time) const {
    ...
    const int i = findTimeId(time);
    if(i > -1) {  // _stampleStorage contains sample at given time
        return _stampleStorage[i].sample;  // don't use getTimesAndValues, because this would iterate over the complete _stampleStorage.
    }

    if(!_bspline.has_value()) {
        auto [times, values] = getTimesAndValues();
        _bspline.emplace(times, values, usedDegree);
    }
    
    return _bspline.value().interpolateAt(time);
}
```

**Review by BenjaminRodenberg — CHANGES_REQUESTED** [review]
Generally looks good. Minor comments, but nothing critical.

File: src/time/Storage.cpp (hunk 1 above)
Comment (fsimonis) [reply src/time/Storage.cpp]: Both changes together make a lot of sense :+1:.

We don't need a sentinel value, now that we have optional though `std::optional<int> findTime(double time) const;`

**Review by fsimonis — APPROVED** [review]
