### PR TITLE
Fix PETSc mappings crashing when checking the config

### LINKED ISSUE #1562: config-checker crashes when checking PETSc RBF mappings
**Describe your setup**

Operating system (e.g. Linux distribution and version): Ubuntu 20.04 (VM) & Ubuntu 22.04
preCICE Version: 2.5.0 + develop

Add the versions/commit hashes of further adapter and/or bindings.

**Describe the problem**
`precice-tools check` crashes if the config includes an RBF mapping and preCICE is build with PETSc.

```
Checking precice-config.xml for syntax and basic setup issues...
*** The MPI_Comm_rank() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[tickly:111257] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

**Step To Reproduce**
1. Pick a configuration that uses `<mapping:rbf-X />` 
3. Run `precice-tools check precice-config.xml`
4. Notice the crash

**Expected behaviour**
No crash

**Additional context**

The PETRBFMapping accesses the `rank()` in the constructor.
MPI is not initialized when calling `tooling::checkConfiguration`.

**Likely fix**
In `src/precice/Tooling.cpp` add `include<utils/Parallel.hpp` and in `checkConfiguration`:

```diff
+  utils::Parallel::initializeMPI(nullptr, nullptr);
  xml::configure(config.getXMLTag(), context, filename);
  fmt::print(fmt::emphasis::bold | fg(fmt::color::green), "No major issues detected\n", filename);
+  utils::Parallel::finalizeMPI();
```

### PR DESCRIPTION
**Pull request by fsimonis**
## Main changes of this PR

This PR fixes a crash when checking configurations that require PETSc mappings.

## Motivation and additional information

The constructor request the MPI ranks, which leads to a crash.

Closes #1562

## Author's checklist

* [x] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [x] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [x] I added a test to cover the proposed changes in our test suite.
* [x] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [x] I sticked to C++17 features.
* [x] I sticked to CMake version 3.16.3.
* [x] I squashed / am about to squash all commits that should be seen as one.

### CODE REVIEW

File: src/utils/Parallel.cpp [hunk 1]
```diff
@@ -2,6 +2,7 @@
 #include <algorithm>
 #include <map>
 #include <memory>
+#include <mpi.h>
```
Comment (fsimonis) [inline src/utils/Parallel.cpp:5]:
```suggestion
```
